REPLACE INTO `command` (name, help) VALUES
('npc set phase', 'Syntax: .npc set phase [-guid $guid] #phasemask\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable.\nOptionally you can use the -guid $guid option to specify a spawn id to not have a creature targetted.'),
('npc set phase', 'Syntax: .npc say [-guid $guid] $message\nMake selected creature say specified message.\nOptionally you can use the -guid $guid option to specify a spawn id to not have a creature targetted.'),
('npc textemote', 'Syntax: .npc textemote [-guid $guid] $message\nMake the selected creature send an emote message.\nOptionally you can use the -guid $guid option to specify a spawn id to not have a creature targetted.'),
('npc whisper', 'Syntax: .npc whisper $playerName [-guid $guid] $message\nMake the selected npc whisper #text to  #playerguid.\nOptionally you can use the -guid $guid option to specify a spawn id to not have a creature targetted.'),
('npc cast', 'Syntax: .npc cast $spellId [-p] [-t $creature_id|$player_name] [-i $interval] [-d $duration] [-o $intervalOffset]\nMakes the targetted creature cast spell $spellId.\nOptional arguments:\n-p Specifies that the spell casting should be persisted between server restarts.\n-t $target: Specifies the target of the spell, default is self. Other valid targets are the id of a creature, or the name of a player character. \n-i $interval: Specifies that the spell should be repeated every $interval ms.\n-d $duration: Specifies that the spell should last $duration ms before cancelling the spell.\n-o $offset: Specifies the rest time $offset in ms, this will determine how long an npc will wait before starting the initial spell cast.\n-c $guid: Specifies the caster for the spell should be the creature with GUID $guid'),
('npc set animkit', 'Syntax: .npc set animkit [-guid $guid] $animKitId\nSets the animation kit for the the targeted npc to $animKitId.\nOptionally you can use the -guid $guid option to specify a spawn id to not have a creature targetted.'),
('formation add', 'Syntax: .formation add $formationKey [$guid]\nAdds your current target to the formation with key $formationKey.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.'),
('formation new', 'Syntax: .formation new $formationKey [$guid]\nCreates a new formation identified by formationKey $formationKey with with your current target as its leader.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.'),
('formation remove', 'Syntax: .formation remove [$guid]\nRemoves your current target from its formation.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.'),
('gotomarker', 'Syntax: .gotomarker [$guid]\nTells your currently targetted NPC to go the location where you placed your marker with the marker spell.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.'),
('turntomarker', 'Syntax: .turntomarker [$guid]\nTells your currently targetted NPC to turn to the location where you placed your marker with the marker spell.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.'),
('walktomarker', 'Syntax: .walktomarker [$guid]\nTells your currently targetted NPC to walk to the location where you placed your marker with the marker spell.\nOptionally you can use the $guid option to specify a spawn id to not have a creature targetted.')
;