-- Custom strings to support other customizations

INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(11900, 'Invalid item ID: %u.  Be sure to simply add 200000 to the normal item ID that you want.  Only weapons and armor are available, and no legendaries+.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11901, 'Removed RPitemID = %i, amount = %i from %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11902, 'Command : AddRPitem, itemId = %i, amount = %i', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11903, 'Invalid item ID: %u.  Must be above 200000.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11904, 'You set the targeted NPC to size %2.2f.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11905, 'Player %s, faction is %i, flags is %i.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11906, 'You changed %s ''s Faction to %i, and flags to %i.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11907, 'You have already changed your character''s height the maximum amount of times allowed.  Sorry!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11908, 'You set the size %2.2f of %s. (Permanent)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11909, '%s set your scale (permanent) to %2.2f.  You cannot change your own size anymore!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11910, 'Player %s, faction is %i.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11911, 'You changed %s ''s Faction to %i.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11912, '%s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11913, 'You cannot add restricted item ID: %u.  If you have a legitimate need for it, consult an administrator.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11914, 'You changed your scale from %2.2f to %2.2f.  You have %i scale changes remaining.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11915, 'You have access to all taxi nodes now (until logout).  Be sure to take advantage of this and pick up taxi nodes now as you can only enable this %i more times.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11916, 'Sorry, but you''ve already enabled the taxi cheat three times.  If you have taxi nodes left to discover, you''ll have to get them manually.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11917, 'Your taxi cheat is already enabled, nub!  Make use of it and go pick up as many taxi nodes as you can!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11918, 'You changed the creature spawn (GUID=%i ) faction to %i.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11919, 'You have access to all taxi nodes now (until logout)!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11920, 'Mass-added itemID = %i, amount = %i', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11921, 'Mass-removed itemID = %i, amount = %i', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11922, 'Sound %u played to nearby (in sight) players.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11923, 'You cannot spawn restricted NPC ID: %u.  If you have a legitimate need for it, consult an administrator.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11924, 'Changed your model to: %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11925, 'Forced rename for player %s will be requested at next login, and inserted name in restricted table.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11926, 'Forced rename for player %s (GUID #%u) will be requested at next login, and inserted name in restricted table.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11927, 'An error occurred when trying to retrieve the scale of the targeted GO.  Please mention this to Kretol, noting where this occurred!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11928, 'Sorry, but as a tauren/draenei or gnome, you cannot go above a 1.10 or under 0.9 scale, respectively.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11929, 'You cannot set a scale above 1.1 or under 0.9 until you have an approved profile!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11930, 'You customized your scale from default to %2.2f.  You have %i scale changes remaining.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11931, '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11932, '%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11933, '%d - owner: %s (guid: %u account: %u ) %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11934, 'Total items found for player %s: %u ( inventory %u mail %u auction %u)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11935, 'Your current scale is: %2.2f\nType .help scale for more information using this command.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11936, 'You cannot spawn restricted Object ID: %u.  If you have a legitimate need for it, consult an administrator.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11937, 'Game Object (Entry: %u) have invalid data, but still attempted spawn.  If you do not see anything, please delete it.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11938, 'Character ''%s'' does not seem to exist!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11939, 'Character ''%s'' successfully transferred to account ''%s''', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11940, 'Player visuals refreshed!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
--(11941, '|cffff0000[Server Event]: %s|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
--(11942, '|cffff0000[Automatic]: %s|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11943, 'NPC Name: %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11944, 'Your current LFRP entry: %s\nLast updated: %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11945, 'You do not currently have an LFRP entry.  Use .lfrp followed by a brief LFRP message, or use .help lfrp for available commands.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11946, 'Your LFRP entry has been cleared!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11947, '%s''s LFRP entry has been cleared!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11948, 'Your LFRP entry has been set to: %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11949, '[%s] <%s>: %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11950, 'Total online characters LFRP: %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11951, 'LFRP Characters:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11952, 'Total characters LFRP (Online/Offline): %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11953, 'No online characters are currently listed as LFRP.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11954, 'To list your character as LFRP, use .lfrp!  To see online characters listed as LFRP, use .lfrp list!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11955, 'You must be alive to use the refresh command!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
