CREATE TABLE IF NOT EXISTS `addon_login_msgs` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`prefix` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`message` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`senderGuid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`senderAccountGuid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`senderGuildGuid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
